/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_akhir_prak;
//import java.util.ArrayList;
//import java.util.List;
//import java.swing.table.DefaultTableColumnModel;
//import java.swing.table.DefaultTableModel;
//import javax.swing.table.DefaultTableModel;
//import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class GUI_penjualan extends javax.swing.JFrame {

    /**
     * Creates new form daftar
     */
    public GUI_penjualan() {
        initComponents();
//        DefaultTableModel dataModel = (DefaultTableModel) jTable1.getModel();
//        
//        int rowCount = dataModel.getRowCount();
//        while (rowCount > 0){
//            dataModel.removeRow(rowCount-1);
//            rowCount = dataModel.getRowCount();
//        }
    }
    
//    public void clear() {
//        kode.setText("");
//        nama.setText("");
//        jumlah.setText("");
//        harga.setText("");
//        buttonGroup1.clearSelection();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cetak = new javax.swing.JButton();
        kode = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        jenis = new javax.swing.JTextField();
        merek = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel1.setText("Kode   : ");

        jLabel2.setText("Nama  :");

        jLabel3.setText("Jenis    : ");

        jLabel4.setText("Jumlah : ");

        jLabel5.setText("Harga  : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Data Pembelian");

        ket.setColumns(20);
        ket.setRows(5);
        jScrollPane1.setViewportView(ket);

        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });

        merek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merekActionPerformed(evt);
            }
        });

        jLabel7.setText("Merek    : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kode, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(nama)
                    .addComponent(jumlah)
                    .addComponent(harga)
                    .addComponent(jenis)
                    .addComponent(merek))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(merek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        toko obj= new toko();
        grosir gro = new grosir();
        makanan maem = new makanan();
        minuman mimik = new minuman();
        obj.getkode(kode.getText());
        obj.nama=nama.getText();
        obj.getjenis(jenis.getText());
        obj.merk=merek.getText();
        if (jenis.getText().equals(gro.setjenis())){
            gro.harga=Integer.parseInt(harga.getText());
            gro.jumlah=Integer.parseInt(jumlah.getText());
            ket.append("Struk Belanja\n");
            ket.append("--------------------------------------------------------\n");
            ket.append("Kode Barang : " + obj.setkode()+"\n");
            ket.append("Nama Barang : " + obj.nama+"\n");
            ket.append("Jenis Barang : " + gro.setjenis()+"\n");
            ket.append("Merek : " + obj.merk+"\n");
            ket.append("Harga Barang : " +gro.harga+ "\n");
            ket.append("Jumlah Barang : " + gro.jumlah+"\n");
            if (gro.jumlah>=gro.min_or){
                ket.append("Diskon Barang : " + gro.diskon(10) + "\n");
            }
            ket.append("--------------------------------------------------------\n");
            ket.append("Harga Total : " + gro.hittod() +"\n");
        }else if(jenis.getText().equals(maem.setjenis())){
            maem.harga=Integer.parseInt(harga.getText());
            maem.jumlah=Integer.parseInt(jumlah.getText());
            ket.append("Struk Belanja\n");
            ket.append("--------------------------------------------------------\n");
            ket.append("Kode Barang : " + obj.setkode()+"\n");
            ket.append("Nama Barang : " + obj.nama+"\n");
            ket.append("Jenis Barang : " + maem.setjenis()+"\n");
            ket.append("Merek : " + obj.merk+"\n");
            ket.append("Harga Barang : " +maem.harga+ "\n");
            ket.append("Jumlah Barang : " + maem.jumlah+"\n");
            if (maem.jumlah>=3){
                ket.append("Diskon Barang : " + maem.diskon + "\n");
            }else{
                maem.diskon=0;
            }
            ket.append("--------------------------------------------------------\n");
            ket.append("Harga Total : " + maem.hittod()+"\n");
        }else if(jenis.getText().equals(mimik.setjenis())){
            mimik.harga=Integer.parseInt(harga.getText());
            mimik.jumlah=Integer.parseInt(jumlah.getText());
            ket.append("Struk Belanja\n");
            ket.append("--------------------------------------------------------\n");
            ket.append("Kode Barang : " + obj.setkode()+"\n");
            ket.append("Nama Barang : " + obj.nama+"\n");
            ket.append("Jenis Barang : " + mimik.setjenis()+"\n");
            ket.append("Merek : " + obj.merk+"\n");
            ket.append("Harga Barang : " +mimik.harga+ "\n");
            ket.append("Jumlah Barang : " + mimik.jumlah+"\n");
            if (obj.jumlah>=2){
                ket.append("Diskon Barang : " + mimik.diskon + "\n");
            }else{
                mimik.diskon=0;
            }
            ket.append("--------------------------------------------------------\n");
            ket.append("Harga Total : " + mimik.hittod() +"\n");
        }else{
            ket.append("Struk Belanja\n");
            ket.append("--------------------------------------------------------\n");
            ket.append("Kode Barang : " + obj.setkode()+"\n");
            ket.append("Nama Barang : " + obj.nama+"\n");
            ket.append("Jenis Barang : " + obj.setjenis()+"\n");
            ket.append("Merek : " + obj.merk+"\n");
            ket.append("Harga Barang : " +obj.harga+ "\n");
            ket.append("Jumlah Barang : " + obj.jumlah+"\n");
            ket.append("--------------------------------------------------------\n");
            ket.append("Harga Total : " + obj.hittod() +"\n");
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void merekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cetak;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextArea ket;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField merek;
    private javax.swing.JTextField nama;
    // End of variables declaration//GEN-END:variables
}
